class Tone
  def pwm_tone_init: (Integer) -> void
  def pwm_tone_set_tones: (Array[Integer], Integer) -> void
  def pwm_tone_start: () -> void

  def initialize: (Integer) -> void
  def set_tones: (Array[Integer], Integer) -> void
  def start: () -> void
end